version: '3.4'

services:
  db:
    image: mysql/mysql-server:8.0.23
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/my.cnf
      - ./log/mysql:/var/log/mysql
networks:
  default:
    ipam:
      config:
        - subnet: 192.168.1.0/8
